name: 'de_zoomcamp_ds'
version: '1.0.0'
config-version: 2

require-dbt-version: [">=1.7.0", "<3.0.0"]

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  de_zoomcamp_ds:
    staging:
      +materialized: view

    intermediate:
      +materialized: view

    marts:
      +materialized: table